-- MySQL
--
-- 컬럼명을 잘 확인할 것
-- 
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
    FROM ANIMAL_INS AS INS
    JOIN ANIMAL_OUTS AS OUTS
        ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE (OUTS.SEX_UPON_OUTCOME LIKE "Neutered%" 
        OR OUTS.SEX_UPON_OUTCOME LIKE "Spayed%")
        AND INS.SEX_UPON_INTAKE LIKE "Intact%"
    ORDER BY INS.ANIMAL_ID